version: '3'

services:
  nginx:
    image: lawyer-nginx:latest
    ports:
      - 80:80
    build:
      context: .
      dockerfile: deploy/nginx/Dockerfile
    depends_on:
      - app
    restart: always
    networks:
      - web
      - project
    environment:
      VIRTUAL_HOST: evomark.ru
      LETSENCRYPT_HOST: evomark.ru

  app:
    image: lawyer-python:latest
    build:
      context: .
      dockerfile: deploy/python/Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
    restart: always
    networks:
      - project

  db:
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: lawyer
      POSTGRES_USER: lawyer
      POSTGRES_PASSWORD: lawyer
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    networks:
      - project

volumes:
  db:
  app:

networks:
  project:
  web:
    external:
      name: web
