version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: deploy/nginx/Dockerfile
    ports:
      - 80:80
    restart: always
    depends_on:
      - python

  python:
    build:
      context: .
      dockerfile: deploy/python/Dockerfile
    restart: always
    environment:
      DEBUG: 'False'
      DB_NAME: db
      DB_USER: db
      DB_PASSWORD: db
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_NAME: db
