# Generated by Django 4.0.2 on 2022-07-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='solvedapplication',
            options={'verbose_name': 'Решённая задача', 'verbose_name_plural': 'Решённые задачи'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_notified',
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.CharField(max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='application',
            name='person_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='solvedapplication',
            name='history',
            field=models.TextField(verbose_name='История'),
        ),
        migrations.AlterField(
            model_name='solvedapplication',
            name='result',
            field=models.TextField(verbose_name='Итог'),
        ),
        migrations.AlterField(
            model_name='solvedapplication',
            name='title',
            field=models.CharField(max_length=35, verbose_name='Заголовок'),
        ),
    ]
