# Generated by Django 4.0.2 on 2022-07-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_check_trademark',
            field=models.BooleanField(default=False, verbose_name='Проверка знака'),
            preserve_default=False,
        ),
    ]
