# Generated by Django 4.0.2 on 2022-07-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_application_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='person_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
