# Generated by Django 4.0.2 on 2022-07-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_application_is_check_trademark'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Заявка выполнена'),
            preserve_default=False,
        ),
    ]
