# Generated by Django 4.0.2 on 2022-07-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_application_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='trademark',
            field=models.FileField(blank=True, null=True, upload_to='trademarks/', verbose_name='Товарный знак'),
        ),
    ]
